# Generated by Django 4.2.11 on 2024-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bangumi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('rss', models.CharField(max_length=600)),
                ('re_rule', models.CharField(max_length=600)),
                ('bgm_id', models.IntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
