# Generated by Django 4.2.11 on 2024-03-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AniQuest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangumi',
            name='re_rule',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=260)),
                ('have_downloaded', models.BooleanField(default=False)),
                ('download_time', models.DateTimeField()),
                ('bangumi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AniQuest.bangumi')),
            ],
        ),
    ]
