# Generated by Django 4.2.11 on 2024-03-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniQuest', '0002_alter_bangumi_re_rule_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='scrapped',
            field=models.BooleanField(default=False),
        ),
    ]
