# Generated by Django 4.2.11 on 2024-03-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AniQuest', '0003_record_scrapped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='scrapped',
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrapped', models.BooleanField(default=False)),
                ('bangumi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AniQuest.bangumi')),
            ],
        ),
    ]
