# Generated by Django 4.2.11 on 2024-03-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniQuest', '0004_remove_record_scrapped_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='file_name',
            field=models.CharField(default='', max_length=260),
        ),
    ]
