# Generated by Django 4.2.11 on 2024-09-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniQuest', '0005_episode_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangumi',
            name='poster',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='posters'),
        ),
    ]
